from typing import overload, Optional, ClassVar, Sequence
from PySide6.QtCore import QObject, Qt, QPointF, QSizeF, QRectF, QMarginsF
from PySide6.QtGui import QColor, QPen, QImage, QFont, QPainter
from PySide6.QtWidgets import QWidget
from PySide6.QtPositioning import QGeoCoordinate

class MapPoint:
    def __init__(self) -> None: ...
    @overload
    def __init__(self, screenPoint: QPointF) -> None: ...
    @overload
    def __init__(self, geoPoint: QGeoCoordinate) -> None: ...
    
    def isValid(self) -> bool: ...
    def screenPoint(self, map: 'SimpleMapView') -> QPointF: ...
    def geoPoint(self, map: 'SimpleMapView') -> QGeoCoordinate: ...

class MapSize:
    def __init__(self) -> None: ...
    @overload
    def __init__(self, screenSize: QSizeF) -> None: ...
    @overload
    def __init__(self, geoSize: QGeoCoordinate) -> None: ...
    
    def isValid(self) -> bool: ...
    def screenSize(self, map: 'SimpleMapView', topLeft: MapPoint) -> QSizeF: ...
    def geoSize(self, map: 'SimpleMapView', topLeft: MapPoint) -> QGeoCoordinate: ...

class TileServers(QObject):
    INVALID: ClassVar[str] = ...
    OSM: ClassVar[str] = ...
    OPENTOPOMAP: ClassVar[str] = ...
    GOOGLE_MAP: ClassVar[str] = ...
    GOOGLE_SAT: ClassVar[str] = ...
    GOOGLE_LAND: ClassVar[str] = ...
    CARTODB_POSITRON: ClassVar[str] = ...
    CARTODB_DARK_MATTER: ClassVar[str] = ...
    THUNDERFOREST_TRANSPORT: ClassVar[str] = ...
    THUNDERFOREST_LANDSCAPE: ClassVar[str] = ...
    THUNDERFOREST_OUTDOORS: ClassVar[str] = ...
    ESRI_WORLD_STREET_MAP: ClassVar[str] = ...
    ESRI_WORLD_IMAGERY: ClassVar[str] = ...

    def __init__(self, parent: Optional[QObject] = ...) -> None: ...

class MapItem(QObject):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    def pen(self) -> QPen: ...
    def setPen(self, pen: QPen) -> None: ...
    
    def penColor(self) -> QColor: ...
    def setPenColor(self, color: QColor) -> None: ...
    
    def penWidth(self) -> float: ...
    def setPenWidth(self, width: float) -> None: ...
    
    def penStyle(self) -> Qt.PenStyle: ...
    def setPenStyle(self, style: Qt.PenStyle) -> None: ...
    
    # Virtual method, technically usable but rarely called directly in Python
    # def render(self, renderer: QPainter) -> None: ...

    # Signals
    def changed(self) -> None: ...
    def penChanged(self) -> None: ...

class MapEllipse(MapItem):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    def alignmentFlags(self) -> Qt.Alignment: ...
    def setAlignmentFlags(self, f: Qt.Alignment) -> None: ...
    
    def position(self) -> MapPoint: ...
    @overload
    def setPosition(self, position: QPointF) -> None: ...
    @overload
    def setPosition(self, position: QGeoCoordinate) -> None: ...
    @overload
    def setPosition(self, position: MapPoint) -> None: ...
    
    def size(self) -> MapSize: ...
    @overload
    def setSize(self, s: QSizeF) -> None: ...
    @overload
    def setSize(self, s: QGeoCoordinate) -> None: ...
    @overload
    def setSize(self, s: MapSize) -> None: ...
    
    def backgroundColor(self) -> QColor: ...
    def setBackgroundColor(self, c: QColor) -> None: ...

    # Signals
    def positionChanged(self) -> None: ...
    def sizeChanged(self) -> None: ...
    def backgroundColorChanged(self) -> None: ...

class MapRect(MapEllipse):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    @overload
    def setBorderRadius(self, r: float) -> None: ...
    @overload
    def setBorderRadius(self, topLeft: float, topRight: float, bottomRight: float, bottomLeft: float) -> None: ...
    
    # Signals
    def borderRadiusChanged(self) -> None: ...

class MapImage(MapRect):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    def image(self) -> QImage: ...
    @overload
    def setImage(self, imagePath: str) -> None: ...
    @overload
    def setImage(self, img: QImage) -> None: ...
    
    def aspectRatioMode(self) -> Qt.AspectRatioMode: ...
    def setAspectRatioMode(self, m: Qt.AspectRatioMode) -> None: ...
    
    # Signals
    def imageChanged(self) -> None: ...

class MapText(MapRect):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    def text(self) -> str: ...
    def setText(self, t: str) -> None: ...
    
    def textFlags(self) -> int: ...
    def setTextFlags(self, flags: int) -> None: ...
    
    def textColor(self) -> QColor: ...
    def setTextColor(self, c: QColor) -> None: ...
    
    def font(self) -> QFont: ...
    def setFont(self, f: QFont) -> None: ...
    
    def textPadding(self) -> QMarginsF: ...
    @overload
    def setTextPadding(self, p: QMarginsF) -> None: ...
    @overload
    def setTextPadding(self, left: float, top: float, right: float, bottom: float) -> None: ...
    
    # Signals
    def textChanged(self) -> None: ...
    def textFlagsChanged(self) -> None: ...
    def textColorChanged(self) -> None: ...
    def fontChanged(self) -> None: ...
    def textPaddingChanged(self) -> None: ...

class MapLines(MapItem):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    def points(self) -> list[MapPoint]: ...
    def setPoints(self, points: Sequence[MapPoint]) -> None: ...

class MapPolygon(MapLines):
    def __init__(self, parent: Optional[QObject] = ...) -> None: ...
    
    def backgroundColor(self) -> QColor: ...
    def setBackgroundColor(self, c: QColor) -> None: ...
    
    # Signals
    def backgroundColorChanged(self) -> None: ...

class SimpleMapView(QWidget):
    
    class TileServerSource:
        Invalid: ClassVar['SimpleMapView.TileServerSource'] = ...
        Remote: ClassVar['SimpleMapView.TileServerSource'] = ...
        Local: ClassVar['SimpleMapView.TileServerSource'] = ...
        Resource: ClassVar['SimpleMapView.TileServerSource'] = ...

    def __init__(self, parent: Optional[QWidget] = ...) -> None: ...
    
    # Properties
    def minZoomLevel(self) -> int: ...
    def setMinZoomLevel(self, minZoomLevel: int) -> None: ...
    
    def maxZoomLevel(self) -> int: ...
    def setMaxZoomLevel(self, maxZoomLevel: int) -> None: ...
    
    def zoomLevel(self) -> int: ...
    def setZoomLevel(self, zoomLevel: int) -> None: ...
    
    def latitude(self) -> float: ...
    def setLatitude(self, latitude: float) -> None: ...
    
    def longitude(self) -> float: ...
    def setLongitude(self, longitude: float) -> None: ...
    
    def center(self) -> QGeoCoordinate: ...
    @overload
    def setCenter(self, center: QGeoCoordinate) -> None: ...
    @overload
    def setCenter(self, latitude: float, longitude: float) -> None: ...
    
    def tileServer(self) -> str: ...
    @overload
    def setTileServer(self, tileServer: str, wait: bool = True) -> None: ...
    @overload
    def setTileServer(self, tileServers: Sequence[str]) -> None: ...
    
    def tileServerSource(self) -> SimpleMapView.TileServerSource: ...
    
    def backupTileServers(self) -> list[str]: ...
    @overload
    def addBackupTileServer(self, tileServer: str) -> None: ...
    @overload
    def addBackupTileServer(self, tileServers: Sequence[str]) -> None: ...
    def clearBackupTileServers(self) -> None: ...
    
    def isZoomLocked(self) -> bool: ...
    def setLockZoom(self, lock: bool) -> None: ...
    def lockZoom(self) -> None: ...
    def unlockZoom(self) -> None: ...
    
    def isGeolocationLocked(self) -> bool: ...
    def setLockGeolocation(self, lock: bool) -> None: ...
    def lockGeolocation(self) -> None: ...
    def unlockGeolocation(self) -> None: ...
    
    def isMouseWheelZoomDisabled(self) -> bool: ...
    def setDisableMouseWheelZoom(self, disable: bool) -> None: ...
    def enableMouseWheelZoom(self) -> None: ...
    def disableMouseWheelZoom(self) -> None: ...
    
    def isMouseMoveMapDisabled(self) -> bool: ...
    def setDisableMouseMoveMap(self, disable: bool) -> None: ...
    def enableMouseMoveMap(self) -> None: ...
    def disableMouseMoveMap(self) -> None: ...
    
    def markerIcon(self) -> QImage: ...
    @overload
    def setMarkerIcon(self, icon: QImage) -> None: ...
    @overload
    def setMarkerIcon(self, iconPath: str) -> None: ...
    
    # Invokables
    @overload
    def addMarker(self, latitude: float, longitude: float) -> MapImage: ...
    @overload
    def addMarker(self, position: QGeoCoordinate = ...) -> MapImage: ...
    
    def downloadTiles(self, path: str, p1: QGeoCoordinate, p2: QGeoCoordinate, z1: int, z2: int) -> None: ...
    
    # Converters
    @overload
    def geoCoordinateToTilePosition(self, latitude: float, longitude: float) -> QPointF: ...
    @overload
    def geoCoordinateToTilePosition(self, geoCoordinate: QGeoCoordinate) -> QPointF: ...
    
    @overload
    def geoCoordinateToScreenPosition(self, latitude: float, longitude: float) -> QPointF: ...
    @overload
    def geoCoordinateToScreenPosition(self, geoCoordinate: QGeoCoordinate) -> QPointF: ...
    
    def tilePositionToGeoCoordinate(self, tilePosition: QPointF) -> QGeoCoordinate: ...
    def tilePositionToScreenPosition(self, tilePosition: QPointF) -> QPointF: ...
    
    def screenPositionToTilePosition(self, screenPosition: QPointF) -> QPointF: ...
    def screenPositionToGeoCoordinate(self, screenPosition: QPointF) -> QGeoCoordinate: ...

    # Signals
    def zoomLevelChanged(self) -> None: ...
    def centerChanged(self) -> None: ...
    def tileServerChanged(self) -> None: ...