name: 'Setup Qt Environment'
description: 'Installs Xvfb and Qt'

inputs:
  qt_version:
    description: 'The version of Qt.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Xvfb (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt install -y xvfb

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ inputs.qt_version }}
        target: desktop
        modules: 'qtpositioning'
        cached: true